import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
    return (
        <>
            <Head>
                <title>Currency convert</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.text_container}>
                    Welcome to my currency converter app!<br/>
                    To convert one currency to another go to <span className={styles.page}>Converter page</span><br/>
                    To see exchange rates relative to the current on go to <span className={styles.page}>Currency page</span>
                </div>
            </main>
        </>
    )
}
